version: "3.1"
services:
  tatonka:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../simulations:/tmp/tatonka/simulations
      - ../config.yaml:/etc/tatonka/config.yaml:ro
    tty: true
    depends_on:
      cassandra:
        condition: service_healthy

  cassandra:
    image: cassandra:4.0
    ports:
        - "9042:9042"
    restart: always
    volumes:
      - ../assets/cassandra:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
